#!/bin/sh
#

case "$1" in
    start)
	insmod /usr/lib/ili9488_fb.ko
	insmod /usr/lib/picocalc_kbd.ko

#	insmod /usr/lib/picocalc_snd_pwm.ko

	dmesg -n 1
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac


exit 0
