#! /bin/sh

[ -f /usr/bin/usb-net-up.sh ] || exit 0

start() {
    nohup /usr/bin/usb-net-up.sh 2>&1 >/dev/null &
}


stop() {
    return
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
